name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17 

    - name: Initialize Go module and tidy
      run: |
        go mod init go.main
        go mod tidy

    - name: Build and Test
      run: go build && go test ./...
